<?php
/**
 * Created by PhpStorm.
 * User: Shahimian
 * Date: 4/2/2016
 * Time: 7:29 PM
 */

namespace shahimian\posts\databases;


use yii\db\Migration;

class Posts extends Migration
{

    function up()
    {
        if($this->getDb()->schema->getTableSchema('posts') == false){
            $this->createTable('posts', [
                'id' => $this->bigPrimaryKey(),
                'user_id' => $this->bigInteger(),
                'title' => $this->text(),
                'content' => $this->text(),
                'is_live_page' => $this->boolean(),
                'created_at' => $this->dateTime(),
                'updated_at' => $this->dateTime(),
            ], 'ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_persian_ci');
        }
        return parent::up(); // TODO: Change the autogenerated stub
    }

}